[Server]
Host = "0.0.0.0"
Port = 8080
CertFile=""
KeyFile=""

[Log]
LogFile = "/data/gin-api-frame/log/gin-api-frame.log"
# BackTrackLevel = "debug"
LogLevel = "debug"
LogFormat = "text"
EnableForceColors = true

[Database]
User = "root"
Password = "xxx"
Addr = "127.0.0.1:3600"
DBName = "instance"

[Etcd]
Endpoints = "https://127.0.0.1:2379"
CertFile = "/path/etcd-client.crt"
KeyFile = "/path/etcd-client.key"
CAFile = "/path/ca.crt"
JobQueueKey = "prefix"
